### ISSUE TITLE
그룹리스트 페이지 실제 data get 하여 구현

### ISSUE THREAD

**Issue by degose** [degose/Bond#88]
그룹리스트 페이지 실제 data get 하여 구현

**Comment by realkth** [comment]
지금 백엔드 api에서 데이터 받아뿌리는거죠?

**Comment by degose** [comment]
네 그렇습니다. api는 401에러가 떠서 못하고 있고, firebase는 get이 되는데 firebase에서 그룹 하나를 지워도 view에는 그대로 있어서 가져와진게 맞는지 모르겠습니다.

**Comment by realkth** [comment]
확인했습니다..백엔드가 제공한 api에 의하면 401 error는 사용자 권한 문제인데 코드 리뷰 후 백엔드와의 행아웃 미팅에서 질문을 통해 해결해보겠습니다.

**Comment by realkth** [comment]
degose(세민)가 직접 문의해 해결하셨습니다.
