### ISSUE TITLE
이미지 비율 문제

### ISSUE THREAD

**Issue by realkth** [degose/Bond#95]
이미지 비율이 가변적으로 잘 변하지만 일정 포인트 이하에서 아래 빈 배경이 남는 현상

**Comment by realkth** [comment]
일단 일정 크기 이하에서 아래 빈 배경이 남는 현상은 수정되었습니다만 현재 아래 배경을 아예 잘라버리기 때문에 개선이 필요합니다.

**Comment by realkth** [comment]
프로필 사진 비율 문제 해결하셨습니다. (degose)

**Comment by realkth** [comment]
다른 이미지들 비율 문제 다시 세민님(degose)께서 해결하시기로 하셔서 다시 오픈합니다.

**Comment by degose** [comment]
img요소를 감싼 wrapper에 position relative를 준 뒤에 height 값을 고정시켜주고, img는 position absolute를 주고 top: 30%, transeform: translateY(-30%)를 줘서 30%높이값을 갖게하고, width: auto, min-height: 100%로 주어 반응형일 때에도 이미지 비율이 유지되게 구현하였습니다.
